# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
        name: (.ipynb) remove metadata
        args:
          ["--remove-kernel-metadata", "--pin-patterns", "[pin];[donotremove]"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: (.py) Black
        args: ["--line-length=200"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: (.py) Sort imports

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        name: (.py) Pylint
        exclude: ^tests/
        args: ["--disable=E0401,C0114,C0301,E0402,R0903,E1121,R1705"]
